### ISSUE TITLE
Hue Beyond Pendant and Ceiling recognised as Unknown Zigbee Device

### ISSUE THREAD

**Issue by mdzwarts** [sebbebebbe/com.philips.hue.zigbee#112]
Selected to add the Hue Beyond Pendant tile to be added to Homey, a device is found to be paired, but fails with the message: “No compatible Homey App has been found. Added as basic Zigbee device.” An Unknown Zigbee device shows up in homey, non functional. Can you check/correct so that this works? Its the last step for me to replace the Hue Bridge entirely. 

Hue Beyond Pendant consist of HBL002.
Hue Beyond Ceiling consists of HBL003.

Thanks in advance

**Comment by sebbebebbe** [comment]
Noted, will be added eventually.

**Comment by sebbebebbe** [comment]
I just checked and both those two id:s has been added since v 1.4.0. Did you get the id:s from looking at the generic zigbee device properties?

**Comment by MichaelHendriks** [comment]
LWA001 (Philips Hue white) zigbee & bluetooth don’t support dimm function.
It is the same problem as the text above.
Only on/off function works

**Comment by sebbebebbe** [comment]
Please send the detailed information from the Unknown ZigBee device that has been added.

For the following:
- HBL002
- HBL003
- LWA001

**Comment by MikeymRx** [comment]
Is this enough?



Michael Hendriks

Verstuurd vanaf mijn iPhone

**Comment by MichaelHendriks** [comment]
Hi, this is the Philips Hue light set.

https://www.bol.com/nl/p/philips-hue-white-e27-duopack-bluetooth/9200000117194520/

**Comment by MikeymRx** [comment]
This is the information you need.

Property: Value
ID: c2f51918-a00c-47cf-a80f-eb207c53783b
Class: socket (Virtual: light)
Driver: homey:manager:vdevice — zigbeebasic
Ready: Yes
Available: Yes
Warning: No
Custom icon: No

Settings
Key: Value
zb_profile_id: "260"
zb_device_id: "257"
zb_ieee_addr: "0x0017880106b07225"
zb_product_id: "LWA001"
zb_manufacturer_name: "Philips"

Van: Sebastian Johansson
Verzonden: dinsdag 24 september 2019 20:08
Aan: sebbebebbe/com.philips.hue.zigbee
CC: MikeymRx; Manual
Onderwerp: Re: [sebbebebbe/com.philips.hue.zigbee] Hue Beyond Pendant andCeiling recognised as Unknown Zigbee Device (#112)

Please send the detailed information from the Unknown ZigBee device that has been added.
For the following:
• HBL002
• HBL003
• LWA001
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by MichaelHendriks** [comment]
Property: Value
ID: c2f51918-a00c-47cf-a80f-eb207c53783b
Class: socket (Virtual: light)
Driver: homey:manager:vdevice — zigbeebasic
Ready: Yes
Available: Yes
Warning: No
Custom icon: No
 
Settings
Key: Value
zb_profile_id: "260"
zb_device_id: "257"
zb_ieee_addr: "0x0017880106b07225"
zb_product_id: "LWA001"
zb_manufacturer_name: "Philips"

**Comment by Gemeni123** [comment]
HBL002 & HBL003 That started the thread is supported

Adding LWA001 to the ToDo list
