### ISSUE TITLE
[Feature request] Dim level in flow conditions

### ISSUE THREAD

**Issue by azurit** [sebbebebbe/com.philips.hue.zigbee#178]
Hi,

could it be possible to add current dim level of bulbs into conditions when creating a flow? I would like to set my wireless button to something like this:
 - single click to turn on or off the bulbs
 - double click to switch between 50% and 100% of dim level

Thank you.

**Comment by JohanBendz** [comment]
Thanks for the great idea, I will take this into consideration and see if/how I can implement it.

**Comment by JohanBendz** [comment]
Hi @azurit, I have looked into this and the best solution is to use the current cards and tags instead of adding extra cards or tags. Every bulb has tag values for current settings, if you test that value in your flow you should be able to achieve what you ask for.

Eg. test in condition part of the flow if a lights dim value [use logic card] is more, same or less than a value. Based on this you can set a light to a dim value. 

Example:
Your light is at 50%, you press the button and the flow trigger. In the condition part you check if the value is less than 51%, if so you set the light to 100% in the action part of the script. If the light value  is at more than 51% you set it to 50% in the action part.

Would this work for you?

**Comment by azurit** [comment]
Hi @JohanBendz, sorry, didn't noticed it's there! Looks ok like this, thank you.

Little note: Value of dim level in logic card is represented with float between 0.0 and 1.0 BUT everywhere else it's integer between 0 and 100.
