### ISSUE TITLE
Homey v 5.0

### ISSUE THREAD

**Issue by kjettern** [sebbebebbe/com.philips.hue.zigbee#204]
Homey v5.0 is coming up. This plugin needs the new zigbee framework to work.

**Comment by JohanBendz** [comment]
Been working on an update since some time. Released after firmware update is done.

**Comment by bramoosterhuis** [comment]
@JohanBendz how far is the SDK 3 update going? Since I forgot to switch of the experimental updates I now have 5.0.0-RC running. I didn't saw any branches regarding SDK3 so in order to switch off my bulbs I started to fix the new zigbee stuff here: https://github.com/bramoosterhuis/com.philips.hue.zigbee/tree/feature/homey-sdk3-support

**Comment by JohanBendz** [comment]
Hi @bramoosterhuis and everyone else waiting for the update.

The prerelease to developers and now to experimental did perfectly allign with my summer vacation and it appears my family does not consider developing Homey apps as holiday ;) 

I am now back home after spending time with family and friends and expect to finish the update within a week or so.
