### ISSUE TITLE
Philips Hue Lightstrip Outdoor 5M - Unknown Zigbee device

### ISSUE THREAD

**Issue by versluijs** [sebbebebbe/com.philips.hue.zigbee#239]
Hi,

I have a new Philips Hue Lightstrip Outloor 5M, but unfortunately it is not yet fully recognized in Homey. I already have 2 of the same Lightstrips that are working fine.

Can you make this device supported in the app?

Producent ID: Philips
Product ID: LCL003
Device ID: 269
Profile ID: 260

Thanks
Sven

**Comment by JohanBendz** [comment]
Hi @versluijs. The LCL003 device is added to the version of the app that runs on firmware 5, and from your information I see you run firmware 4.2 (or below). If you have lightstrips that work today I guess they have other product ID's (not LCL003), can this be so? Sadly I am unable to update the app for formware 4.2 (or below) since the app store does not support doing so after the firmware 5 version has been published.

**Comment by versluijs** [comment]
Hi Johan, thank your for the quick reply and that the issue is solved in the newer version of the app. You are correct that I am still running on v4.x of the firmware.
