### ISSUE TITLE
Add Homey device for Aurelle panel not working?

### ISSUE THREAD

**Issue by joepwijers** [sebbebebbe/com.philips.hue.zigbee#372]
I have a Homey Pro with the app for Hue without bridge and want to add my brand new Hue Aurelle panel as a device.
When starting to add this device the app requests to toggle the bulb (I assume take it off power and back on?).
Nothing happens.
It suggests if nothing happens to reset the lamp with hue switch. It came with a dimmer switch (3rd gen) so I did the reset procedure (keep the switch close and hold the on/off button 10 seconds to see the light switch on/off 3 times)
Still, nothing happens.
I tried all 3 variants of the Aurelle (panel light, which is written on the box, rectangular, which it is, and square, just to try them all)
None of them works.
I was at first thinking it could be the distance or the concrete between homey and the lamp, but at the same spot I could add the dimmer switch as a Homey device and trigger flows. So ... what is the problem?

I hope you can help me?

Thanks,
J.

**Comment by JohanBendz** [comment]
Hi @joepwijers, try disabling the app and pair the devices as Generic Zigbee.

If this still does not work the issue is either with Homey or the devices and not with the app.
If it works please interview the units (https://tools.developer.homey.app/tools/zigbee) and get back to me with this info.

In the event you are unable to add the devices as Generic Zigbee there are a number of things you can try.
- Make sure to have several routing Zigbee units among the first 10 added devices
- Make a full restart of Homey
- Swap the power adapter to a new/more powerful one (>2.1 A)

If you still have issue there are a few more things to try, but before doing so please contact Athom.
- These steps include stuff like resetting Zigbee and reinstalling the Homey operating system.. only to be used if you really really have tested everything else and there is a backup in place to restore from.
