### ISSUE TITLE
Outdoor Motion Sensor shows as Outdoor Occupancy Sensor once added

### ISSUE THREAD

**Issue by wsu-runner** [sebbebebbe/com.philips.hue.zigbee#468]
Using the test app ([here](https://homey.app/en-us/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/)) I've been able to successfully add/use the non-outdoor motion sensor as both occupancy and motion sensors within the app, but when adding the outdoor sensor it shows up as Outdoor Occupancy Sensor whether I select occupancy or motion during pairing.

A minor issue, sharing mostly as an FYI. I'd like to disable the sensor based on certain events and I believe that option only exists for motion sensors, not for occupancy sensors.

Thanks for the app - I appreciate the time/effort you've put into it!

**Comment by JohanBendz** [comment]
Hi @wsu-runner, there is no option to disable the sensor in either version of the drivers. If you need this behavior I suggest solving it in a flow. If the device adds as an Occupancy sensor even if you choose the motion sensor it's because the firmware in the device is updated and only work with the new code.
