### ISSUE TITLE
Hue effects

### ISSUE THREAD

**Issue by blutch32** [sebbebebbe/com.philips.hue.zigbee#475]
Can you please add the candle effects and fire effects to the lights ?

**Comment by JohanBendz** [comment]
Hi @blutch32, I have tested this quite a while and find that using Homey to emulate a candle effect for one or two devices works great, but adding more lights will stress your Zigbee network.. and since I don't want people to blame the app for bad implementations that cause the Zigbee network to halt or even breake I have decided not to add this feature.
