### ISSUE TITLE
SML001 Sensor gives red exclamation mark

### ISSUE THREAD

**Issue by robiebab** [sebbebebbe/com.philips.hue.zigbee#477]
First off all thanks for this wonderful app, i use it a lot!!  i only have one issue: red exclamation mark on SML001 after reboot or after a while using softwareversion >= v.2.0.42  . this happed after the zigbee update v.2.0.41-> v.2.0.42. after re-adding the device it solves it for a few days. the devices that have the red exclamation mark still function, you can only not view the status page and see a exclamation mark. i think something is saying zigbee device you are not ok, but it is :P.

diagnostic reportid:
8e962ad0-f9e9-45f6-8cb3-b9b5cba66f73

homey pro 2023
Philips Hue, without the bridge  v2.0.44

**Comment by nogdose** [comment]
Hi, 
Having similar situation with two SML001. In Homey can see  "Zigbee device xx left the network" - notifications after which the device details cannot be accessed.  Both motion sensors still seem to detect activity because flows for the rooms work.  Both devices reply to ping done from developer page. 

app v2.0.35
Homey 10.0.1
36 Zigbee devices of which 6 SML001's of which 2 now failing

**Comment by TheOnlyBrad** [comment]
Same here. Motion sensor is suddenly displayed as offline ("Device not available / timeout") including red exclamation mark in the related Homey tile. However, the measured values ​​of all sensors (brightness, temperature and motion detection) can still be used in flows, but they are NOT displayed. Using of "Repair" function unfortunately doesn´t work. Distance from sensor to Homey is about 3 meters, so that can´t be a reason. The only way to solve the problem is to separate and pair the sensor again... very annoying.

**Comment by lgrubbmo** [comment]
Hi.

I have the same problem with two outdoor motion sensors (SML004). It seems like the problem appears at the same time on them both. Restarting the homey does not fix the problem, but restarting only the hue app on the homey fixes it for some hours.

**Comment by JohanBendz** [comment]
Hi all.
I'm looking into this, it's a timing issue with Zigbee network not being available and/or the devices being in sleep mode on init.

**Comment by JohanBendz** [comment]
Please try the new version, if the problem persist please start a new issue and add the code for a fresh diagnostic report from the app.
