### ISSUE TITLE
cant add hue motion sensor

### ISSUE THREAD

**Issue by Olarsen96** [sebbebebbe/com.philips.hue.zigbee#495]
Hi, have added 1 hue motion sensor, and it works :-) but i tried to add one more, and it came like a unknown zigbee product.. have reset and tried many times

**Comment by Mortnd** [comment]
I have the same issue. Only shows up as unknown device 
Resetting doesn't help either
Homey23

edit: I found out that the test version works to add the motion sensor
https://homey.app/nl-nl/app/com.philips.hue.zigbee/Philips-Hue,-without-the-bridge/test/

**Comment by paslotte** [comment]
Same problem here. What is the timeline for releasing the update to the official version?

**Comment by sfynxsfynx** [comment]
Can confirm that this problem is still ongoing. Tried to install a bran dnew Hue Motion Sensor on Homey Pro (early 2019, with all latest updates and apps also up to date).
Then tried the solution from Mortnd (install succeeds with the testversion of Hue without the bridge).  

That worked indeed, but now the MOTION sensor shows up in devices-overview as an OCCUPANCY sensor.  It does detect motion, so for now I can live with it, but it would be nice of the device is recognized as the right type.  

So before releasing the testversion to official, it needs to be adjusted to correct this flaw.

**Comment by Derffie** [comment]
hi Motion sensor indeed is not recognized. However it is in the testversion. So a happy camper hoping to see this version in production soon :-)

**Comment by sfynxsfynx** [comment]
When added as Motion Sensor (Homey, app "Hue without the bridge"), stills adds as OCCUPANCY sensor. Device works, but wrong name.

**Comment by JohanBendz** [comment]
The specific version of the device is supported in the test version.
The device itself is actually an occupancy detector as it sends a report for 1. when it notice presence 2. when presence is no longer noticed. The older motion detector driver is using an app based timer to reset the motion detection. So.. it's actually the old driver that is the faulty one.. :P

Is this a big deal? I can add all versions of the deviced to both drivers so one can choose.. but the old driver is a legacy driver that does not use the full potential of the device.

**Comment by hansrika** [comment]
Aaah... Thanks for the clarification on that.

I run the test version and was gladly seeing that it worked really nice, until today when Homey alerted that my Outdoor Occupancy sensor left the Zigbee network. I couldn't longpress to open the device in Homey but the flow still worked. I had to repair the device. Hopefully this can be fixed. 🙏🙂

**Comment by sfynxsfynx** [comment]
Hello Johan, 

Thanx for your mail, excuse me for my late reaction. Turned out your mail ended up in spam, but luckily I discovered it…
New is better, so let’s use the new driver. 
But for comprehensibility it may be handy to keep the name “motion sensor”, as Philips does so herself and it’s also what the packaging states.



 

Met vriendelijke groeten,

Koert Walraven

 

 

_________________________________________________________________________

 

DJK Multimedia Productions

Klaproosstraat 2
7004 EH  Doetinchem

 

t:   06-26364698

m: ***@***.*** ***@***.***> 

 

Van: Johan Bendz ***@***.***> 
Verzonden: dinsdag 5 december 2023 21:32
Aan: JohanBendz/com.philips.hue.zigbee ***@***.***>
CC: sfynxsfynx ***@***.***>; Comment ***@***.***>
Onderwerp: [Spam] Re: [JohanBendz/com.philips.hue.zigbee] cant add hue motion sensor (Issue #495)

 

The specific version of the device is supported in the test version.
The device itself is actually an occupancy detector as it sends a report for 1. when it notice presence 2. when presence is no longer noticed. The older motion detector driver is using an app based timer to reset the motion detection. So.. it's actually the old driver that is the faulty one.. :P

Is this a big deal? I can add all versions of the deviced to both drivers so one can choose.. but the old driver is a legacy driver that does not use the full potential of the device.
