### ISSUE TITLE
Test version: ZigBee hangs after Homey Pro (2023) restart

### ISSUE THREAD

**Issue by sbhaugen** [sebbebebbe/com.philips.hue.zigbee#497]
Hello, and firstly thank you for this great app. The test version of "Philips Hue, without the bridge" is the only app where I can add the Hue Motion Sensor to Homey Pro 2023.

However, ZigBee stops in the app every time Homey Pro 2023 has been restarted or restarted by it's own. A workaround is to restart only the app. But then the devices have been offline sine Homey restart. Perhaps adding a delayed start for ZigBee in the app would help?

Thank you in advance.

**Comment by goussetg2** [comment]
I have the same problem

**Comment by BenSimonetti** [comment]
I have the same problem. I also installed the test version (2.0.46) to be able to add the 'Hue Motion Sensor'.
I wonder why the version which is installed on Homey Pro is version 2.0.35, while many versions have been introduced since then. The issue with the 'Hue Motion Sensor' was already resolved in version 2.0.39.

**Comment by JohanBendz** [comment]
Thanks for your patience guys, an update of the live version is on it's way. Random hickups are reported especially for the sensors and I have so far no solution for them other than re-pair/restart/battery out/in etc.
