### ISSUE TITLE
Adding smartbutton does not work

### ISSUE THREAD

**Issue by KoertM** [sebbebebbe/com.philips.hue.zigbee#519]
Hi,

When trying to add a HUE SmartButton via HUE without bridge, I cannot get it to work. It looks like the Homey adding of devices just skips the explanation and setup steps, and immediately says “No new device found”. I am already using an older SmartButton, which works like a charm.

Kind regards, 
Koert

**Comment by JohanBendz** [comment]
Hi @KoertM
sadly.. if the device is not even pairing as a generic Zigbee device the problem is not in the app.

Try a new power adapter, restarting Homey, fresh batteries in the device, check for interference with wifi or other Zigbee units etc etc. Contact Athom if the device still does not pair as a generic Zigbee device.

When the device does pair and you are able to use it in the app I would be happy to hear from you again, especially if you have issues using it in the latest test version of this app.
