### ISSUE TITLE
Cannot add Smart Button

### ISSUE THREAD

**Issue by gsommer** [sebbebebbe/com.philips.hue.zigbee#527]
Hi,

I tried to add the Smartt Button, but even after resetting it, it just does not work. The red light comes on for a second, but does not blink. After releasing the button, a yellow light is blinking, but the button is not added to Homey. Am I doing something wrong?

Kind Regards,
Gerhard

**Comment by JohanBendz** [comment]
Hi @gsommer,
sadly.. if the device is not even pairing as a generic Zigbee device the problem is not in the app.

Try a new power adapter, restarting Homey, fresh batteries in the device, check for interference with wifi or other Zigbee units etc etc. Contact Athom if the device still does not pair as a generic Zigbee device.

When the device does pair and you are able to use it in the app I would be happy to hear from you again, especially if you have issues using it in the latest test version of this app.
