### ISSUE TITLE
Hue Tap Dial switch functions. 

### ISSUE THREAD

**Issue by lovegren22** [sebbebebbe/com.philips.hue.zigbee#550]
Hi.

love that Tap dial switch is available now but I do not get how the button settings. Press, long press, hold and release.
Can someone explain a little bit more and confirm that all 4 options are functional. 

In the Hue app there is the option to have 5 scenes per button-press 1x 2x .. but don’t want to use that old hub anymore and only use Homey.

happy for any help to get this wife approved!

**Comment by wojogun** [comment]
Hi!
thanks for integrating tapdial to the commutity app of hue! buttons 1-4 seem to work as expected.
but how can i use the dial wheel for dimlevel of light, colortemperature of light, volume of speakers. 
e.g. i tried to use hue with slow, sat with normal and lightness with fast rotation - but i did not succeed because i did not get any values from the wheel. only a fixed value can be used:
![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/97849645/7b607751-b082-46a4-9aff-fb128c8e9f17)

**Comment by JohanBendz** [comment]
Hi and thanks for the feedback.
@lovegren22, the four buttons each register:
short press and the release after a short press,
long press and the release after a long press,
and you can trigger a flow based on this.

@wojogun, i see your problem.. the current implementation just trigger the flow card based on the action.
This is a way to handle it
![image](https://github.com/JohanBendz/com.philips.hue.zigbee/assets/34488771/9d404848-0030-4b12-b4e3-e0180b932cea)

**Comment by lovegren22** [comment]
Hi.The wheel is not functional then? The buttons I understand but the main purpose of this device is the wheel. 27 feb. 2024 kl. 00:11 skrev Johan Bendz ***@***.***>:﻿
Hi and thanks for the feedback.
@lovegren22, the four buttons each register:
short press and the release after a short press,
long press and the release after a long press,
and you can trigger a flow based on this.
@wojogun, i see your problem.. the current implementation just trigger the flow card based on the action.
This is a way to handle it
image.png (view on web)
