### ISSUE TITLE
Color bulbs state is reset when using the manual switch

### ISSUE THREAD

**Issue by mansica** [sebbebebbe/com.philips.hue.zigbee#6]
I have two color bulbs and they are behaving the same way when using the manual switch. If turned off and on the state is reset and the bulb gets 100% dim level and yellow light no matter what dim level or color was set before turning it off. If I look in the user interface for the bulb it looks correct and it points to the correct values.

**Comment by sebbebebbe** [comment]
Hi @mansica,

This seems to be standard Hue bulb functionality. I am having the same issue. I have solved it by having a sync color and dim level flow so that all my hue bulbs are in sync.

If my bulbs loose power they go to max when turned on again. No matter the setting in Homey. Try reporting it to Athom and see if you get some more detailed answers there.
