### ISSUE TITLE
[Feature] Friends of HUE

### ISSUE THREAD

**Issue by akafester** [sebbebebbe/com.philips.hue.zigbee#70]
Is this something you would consider supporting?

**Comment by sebbebebbe** [comment]
Well it depends :) what it actually means and the current demand for it.

**Comment by akafester** [comment]
Good answer ;) 
Well it's a program that Philips launched that allows third partys to make HUE compatible accessories. 
Niko has launched such a device https://www.niko.eu/enus/article/120-91004
Now I can't figure out how this particular device works, if it's like the Tap og like the Dimmer. 
But in any regards, would you be open for adding support in your app?

**Comment by sebbebebbe** [comment]
Im open for it but i do not think that Athom will allow another brand in the same app.

**Comment by thegnuu** [comment]
@sebbebebbe I'm planning to implement support for Feller switches, should I create a new repo or do you think it might be okay for Athom to add them to your app?

**Comment by sebbebebbe** [comment]
I think it is another app since it´s not Philips Hue.

**Comment by thegnuu** [comment]
In this case, I will try to create a new app as soon as I found the needed data like deviceId and profileId for the configuration. Thank you!

**Comment by gajdur** [comment]
Hey @thegnuu , can i assist somehow? I have the Feller Freind of Hue Switch in deconz.

**Comment by thegnuu** [comment]
Hi @gajdur 

I just wanted to look into this a few weeks ago and I realized that the "original" not zigbee version from the homey team has support for it as a Tap switch (basically it is more or less the same hardware).

It works quite well but I am not really happy with the delay that might happen, because I think the only way to achieve this is to poll the bridge for changes.

Unfortunately I am kinda busy at the moment and I just accept the delay for now, but if you want to start a project to support this I am happy to help :)
